services:
  postgres:
    image: postgres:18
    container_name: postgres-voiceagent
    restart: always
    environment:
      POSTGRES_USER : voiceagent
      POSTGRES_PASSWORD : voiceagent_password
      POSTGRES_DB : voiceagent_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: